name: Command from a comment

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions-ecosystem/action-regex-match@v2
         id: regex-match
         with:
           text: ${{ github.event.comment.body }}
           regex: '^/run-test-suite\s*(\w+)\s*(\w+)\s*(\w+)\s*$'
           
       - if: ${{ steps.regex-match.outputs.match != '' }}
         uses: actions/checkout@v3
       
       - if: ${{ steps.regex-match.outputs.match != '' }}
         uses: ./.github/workwflows/node.js.yml
         with:
           customer: ${{ steps.regex-match.outputs.group3 }}
           env: ${{ steps.regex-match.outputs.group2 }}
           tests: ${{ steps.regex-match.outputs.group1 }}
