name: Command from a comment

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.regex-match.outputs.group1 }}
      customer: ${{ steps.regex-match.outputs.group2 }}
      env: ${{ steps.regex-match.outputs.group3 }}
      sucess: ${{ steps.regex-match.outputs.match != '' }}
    steps:
       - uses: actions-ecosystem/action-regex-match@v2
         id: regex-match
         with:
           text: ${{ github.event.comment.body }}
           regex: '^/run-test-suite\s*(\w+)\s*(\w+)\s*(\w+)\s*$'
       - if: ${{ steps.regex-match.outputs.match != '' }}
         uses: actions/checkout@v3
         
  reuse-workflow:
   needs: build
   if: ${{ needs.build.outputs.sucess }}
   uses: ./.github/workflows/node.js.yml
   with:
     customer: ${{ needs.build.outputs.customer }}
     env: ${{ needs.build.outputs.env }}
     tests: ${{ needs.build.outputs.tests }}
