# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "-Dkarate.env Environment to run tests in"
        required: true
        options:
          - "dev"
          - "qai"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.type }}
