# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "-Dkarate.env Environment to run tests in"
        required: true
        options:
          - "dev"
          - "qai"
      
      customer:
        type: choice
        description: ""
        required: true
        options:
          - "ALL"
          - "abs"
          - "maf"
      
      tests:
        type: string
        description: ""
        required: true


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions-ecosystem/action-regex-match@v2
#         id: regex-match
#         with:
#           text: ${{ github.event.comment.body }}
#           regex: '^/run-test-suite\s*(\w+)\s*(\w+)\s*(\w+)\s*$'
          
      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          github_token: ${{ github.token }}
          check-only-first-line: true
          body: |
            Hello, 
            ${{ inputs.tests }}
            ${{ inputs.customer }}
            ${{ inputs.env }}!
